# Generated by Django 3.2.8 on 2021-10-13 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinebridal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bridalparty',
            name='bridalprofile',
        ),
        migrations.RemoveField(
            model_name='guestlist',
            name='bridalprofile',
        ),
    ]
