# Generated by Django 3.2.8 on 2021-10-13 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinebridal', '0002_auto_20211012_1750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bridalparty',
            name='user',
        ),
        migrations.RemoveField(
            model_name='guestlist',
            name='user',
        ),
    ]
