# Generated by Django 3.2.8 on 2021-10-08 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinebridal', '0002_rename_bridal_online_onlinebridal'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlinebridal',
            name='bestman',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='onlinebridal',
            name='bride',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='onlinebridal',
            name='bridesmaid',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='onlinebridal',
            name='groom',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='onlinebridal',
            name='groomsman',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='onlinebridal',
            name='guest',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='onlinebridal',
            name='maidofhonor',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='onlinebridal',
            name='phone',
            field=models.IntegerField(default=True, max_length=9),
        ),
        migrations.AlterField(
            model_name='onlinebridal',
            name='zip_code',
            field=models.IntegerField(default=True, max_length=5),
        ),
    ]
