# Generated by Django 3.2.8 on 2021-10-08 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinebridal', '0003_auto_20211007_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlinebridal',
            name='flower_girl',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='onlinebridal',
            name='ring_bearer',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='onlinebridal',
            name='phone',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='onlinebridal',
            name='zip_code',
            field=models.IntegerField(default=True),
        ),
    ]
