# Generated by Django 3.2.8 on 2021-10-14 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinebridal', '0003_auto_20211012_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='bridalprofile',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
