# Generated by Django 3.2.8 on 2021-10-08 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinebridal', '0004_auto_20211007_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlinebridal',
            name='phone',
            field=models.CharField(max_length=12),
        ),
    ]
