# Generated by Django 3.2.8 on 2021-10-11 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinebridal', '0006_onlinebridal_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlinebridal',
            name='email',
            field=models.CharField(default=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='onlinebridal',
            name='street',
            field=models.CharField(max_length=50),
        ),
    ]
