# Generated by Django 3.2.8 on 2021-10-11 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinebridal', '0007_auto_20211011_1522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onlinebridal',
            name='bestman',
        ),
        migrations.RemoveField(
            model_name='onlinebridal',
            name='bride',
        ),
        migrations.RemoveField(
            model_name='onlinebridal',
            name='bridesmaid',
        ),
        migrations.RemoveField(
            model_name='onlinebridal',
            name='flower_girl',
        ),
        migrations.RemoveField(
            model_name='onlinebridal',
            name='groom',
        ),
        migrations.RemoveField(
            model_name='onlinebridal',
            name='groomsman',
        ),
        migrations.RemoveField(
            model_name='onlinebridal',
            name='guest',
        ),
        migrations.RemoveField(
            model_name='onlinebridal',
            name='maidofhonor',
        ),
        migrations.RemoveField(
            model_name='onlinebridal',
            name='ring_bearer',
        ),
        migrations.AddField(
            model_name='onlinebridal',
            name='participation',
            field=models.CharField(choices=[(0, 'Bride'), (1, 'Groom'), (2, 'Guest')], default=False, max_length=15),
        ),
    ]
