# Generated by Django 3.2.8 on 2021-10-11 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinebridal', '0008_auto_20211011_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlinebridal',
            name='participation',
            field=models.CharField(choices=[(0, 'Bride'), (1, 'Groom'), (2, 'Guest')], max_length=15),
        ),
    ]
