# Generated by Django 3.2.8 on 2021-10-11 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinebridal', '0011_alter_onlinebridal_participation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlinebridal',
            name='participation',
            field=models.CharField(choices=[(1, 'Bride'), (2, 'Groom'), (3, 'Guest')], max_length=15),
        ),
    ]
