# Generated by Django 3.2.8 on 2021-10-11 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinebridal', '0013_alter_onlinebridal_participation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlinebridal',
            name='participation',
            field=models.CharField(choices=[('0', 'Bride'), ('1', 'Groom'), ('2', 'Guest'), ('3', 'Maid Of Honor'), ('4', 'Bridesmaid'), ('5', 'Bestman'), ('6', 'Groomsmen'), ('7', 'Flower Girl'), ('8', 'Ring Bearer')], max_length=15),
        ),
    ]
