# Generated by Django 3.2.8 on 2021-10-12 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinebridal', '0014_alter_onlinebridal_participation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlinebridal',
            name='email',
            field=models.EmailField(max_length=50),
        ),
    ]
