# Generated by Django 3.2.8 on 2021-10-12 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onlinebridal', '0017_bridalparty_guestlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='bridalparty',
            name='onlinebridal',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='onlinebridal.onlinebridal'),
        ),
        migrations.AddField(
            model_name='guestlist',
            name='onlinebridal',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='onlinebridal.onlinebridal'),
        ),
    ]
