# Generated by Django 3.2.8 on 2021-10-08 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_vendors_business_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendors',
            name='user',
        ),
    ]
