# Generated by Django 3.2.8 on 2021-10-08 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0003_remove_vendors_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vendors',
            new_name='Vendor',
        ),
    ]
